import { Inter, League_Spartan } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
